CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS station_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS vehicle_battery_db;
CREATE DATABASE IF NOT EXISTS support_db;

-- Cấp quyền lại cho chắc
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
FLUSH PRIVILEGES;